import React, { Component } from 'react'
import '../css/spinner.css'

export default class Loading extends Component {
    render() {
        return (
            <div>
                <div class='spinner'>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                    <i>
                        <b></b>
                    </i>
                </div>

            </div>
        )
    }
}
